[env:lolin_s3_pro]
platform = espressif32
board = lolin_s3_pro
framework = arduino
monitor_speed = 115200

build_flags =
  -Wall -Wextra
  -DARDUINO_LOLIN_S3_PRO

lib_deps =
  zinggjm/GxEPD2 @ ^1.5.0
  olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0
