[env:lolin_s3]
platform = espressif32
board = lolin_s3
framework = arduino

; Lolin S3 Pro = ESP32-S3-WROOM-1 N16R8 (16MB Quad Flash + 8MB Octal PSRAM)
; base board lolin_s3 has no PSRAM by default, so override memory layout
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags =
  -DBOARD_HAS_PSRAM
